name: dream_diary
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  provider: ^6.0.3
  awesome_notifications: ^0.6.21
  flutter_svg: ^1.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/group.svg
    - assets/home.svg
    - assets/notes.svg
    - assets/profile.svg
    - assets/reset.svg
  fonts:
    - family: "Druk"
      fonts:
        - asset: assets/fonts/DrukMedium.otf
          weight: 500
        - asset: assets/fonts/DrukBold.otf
          weight: 700
        - asset: assets/fonts/DrukHeavy.otf
          weight: 800
  uses-material-design: true
