name: dream_diary
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  provider: ^6.0.3
  awesome_notifications: ^0.6.21
  flutter_svg: ^1.1.1+1
  image_picker: ^0.8.5+3
  flutter_secure_storage: ^5.0.2
  dio: ^4.0.6
  intl: ^0.17.0
  translatable_text_field: ^1.0.2+3
  theme: ^0.0.2
  themed: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/group.svg
    - assets/home.svg
    - assets/notes.svg
    - assets/profile.svg
    - assets/reset.svg
    - assets/arrow_back.svg
    - assets/arrow_grey.svg
    - assets/add.svg
    - assets/cross.svg
    - assets/pick_image.svg
  fonts:
    - family: "Druk"
      fonts:
        - asset: assets/fonts/DrukMedium.otf
          weight: 500
        - asset: assets/fonts/DrukBold.otf
          weight: 700
        - asset: assets/fonts/DrukHeavy.otf
          weight: 800
  uses-material-design: true
